export const ERROR_CODES = {
    CREATE_SIGHTING_FAILED: 'CREATE_SIGHTING_FAILED',
    FETCH_PUBLIC_SIGHTINGS_FAILED: 'FETCH_PUBLIC_SIGHTINGS_FAILED',
    FETCH_ALL_SIGHTINGS_FAILED: 'FETCH_ALL_SIGHTINGS_FAILED',
    UPDATE_SIGHTING_STATUS_FAILED: 'UPDATE_SIGHTING_STATUS_FAILED',
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',
};